import {StyleSheet} from 'react-native';

export const accessibilityStyles = StyleSheet.create({

    accessibilityButton: {
        borderRadius: 80,
        marginBottom: 130,
        marginLeft: 10,
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        width: 65,
        height: 65,
        justifyContent: 'center',
        padding: 13,
      },
      soundButton: {
        borderRadius: 80,
        marginBottom: 130,
        alignSelf: 'flex-end',
        marginLeft: '81.5%',
        margin: 10,
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        width: 65,
        height: 65,
        justifyContent: 'center',
      },
      voiceCommandButton: {
        borderRadius: 80,
        marginBottom: 210,
        alignSelf: 'flex-end',
        marginLeft: '81.5%',
        margin: 10,
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        width: 65,
        height: 65,
        justifyContent: 'center',
      },
      wheelchairImage: {
        width: 35,
        height: 43,
        justifyContent: 'center',
      },
      wheelchairImageDisabled: {
        width: 50,
        height: 50,
        marginLeft: -5,
      },
      soundImageEnabled: {
        width: 40,
        height: 35,
        margin: 14,
      },
      soundVoiceImageDisabled: {
        width: 50,
        height: 50,
        margin: 8,
      },
      voiceCommandImageEnabled: {
        width: 30,
        height: 44,
        marginLeft: 18,
        margin: 10,
      },
      circleButtonClicked: {
        backgroundColor: '#FFF',
      },
      circleButtonUnclicked: {
        backgroundColor: '#000',
      },
      helpButton: {
        borderRadius: 80,
        marginLeft: 10,
        marginTop: 10,
        position: 'absolute',
        left: 0,
        right: 0,
        width: 45,
        height: 45,
        justifyContent: 'center',
        padding: 13,
      },
      helpButtonText: {
        fontSize: 27,
        fontWeight: 'bold',
        color: '#B3B3B3',
        textAlign: 'center',
        marginTop: -10,
      }
})